/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elevatorproject_douggriffiths;

/**
 *
 * @author doug
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
        myElevator.start();
        person1.start();
        person2.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        personOne = new javax.swing.JLabel();
        person1Call = new javax.swing.JButton();
        person1Floor = new javax.swing.JTextField();
        person1Go = new javax.swing.JButton();
        person1Location = new javax.swing.JTextField();
        person1Where = new javax.swing.JLabel();
        person1WhatFloor = new javax.swing.JLabel();
        person2Where = new javax.swing.JLabel();
        person2WhatFloor = new javax.swing.JLabel();
        personTwo = new javax.swing.JLabel();
        person2Call = new javax.swing.JButton();
        person2Floor = new javax.swing.JTextField();
        person2Go = new javax.swing.JButton();
        person2Location = new javax.swing.JTextField();
        person3Call = new javax.swing.JButton();
        person3Floor = new javax.swing.JTextField();
        person3Go = new javax.swing.JButton();
        person3Location = new javax.swing.JTextField();
        person3Where = new javax.swing.JLabel();
        person3WhatFloor = new javax.swing.JLabel();
        personThree = new javax.swing.JLabel();
        person4WhatFloor = new javax.swing.JLabel();
        personFour = new javax.swing.JLabel();
        person4Call = new javax.swing.JButton();
        person4Floor = new javax.swing.JTextField();
        person4Go = new javax.swing.JButton();
        person4Location = new javax.swing.JTextField();
        person4Where = new javax.swing.JLabel();
        person5WhatFloor = new javax.swing.JLabel();
        personFive = new javax.swing.JLabel();
        person4Call1 = new javax.swing.JButton();
        person5Floor = new javax.swing.JTextField();
        person4Go1 = new javax.swing.JButton();
        person4Location1 = new javax.swing.JTextField();
        person5Where = new javax.swing.JLabel();
        floor1Label = new javax.swing.JLabel();
        floor1 = new javax.swing.JTextField();
        floor2 = new javax.swing.JTextField();
        floor2Label = new javax.swing.JLabel();
        floor3Label = new javax.swing.JLabel();
        floor3 = new javax.swing.JTextField();
        floor4Label = new javax.swing.JLabel();
        floor4 = new javax.swing.JTextField();
        floor5Label = new javax.swing.JLabel();
        floor5 = new javax.swing.JTextField();
        floor7 = new javax.swing.JTextField();
        floor7Label = new javax.swing.JLabel();
        floor8Label = new javax.swing.JLabel();
        floor8 = new javax.swing.JTextField();
        floor9Label = new javax.swing.JLabel();
        floor9 = new javax.swing.JTextField();
        floor11Label = new javax.swing.JLabel();
        floor11 = new javax.swing.JTextField();
        floor6Label = new javax.swing.JLabel();
        floor6 = new javax.swing.JTextField();
        floor10Label = new javax.swing.JLabel();
        floor10 = new javax.swing.JTextField();
        stopButton = new javax.swing.JButton();
        elevatorStatusLabel = new javax.swing.JLabel();
        elevatorStatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(225, 225, 225));

        personOne.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        personOne.setForeground(new java.awt.Color(3, 3, 3));
        personOne.setText("Person 1");

        person1Call.setBackground(new java.awt.Color(225, 225, 225));
        person1Call.setText("Call");
        person1Call.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person1CallActionPerformed(evt);
            }
        });

        person1Floor.setBackground(new java.awt.Color(200, 200, 200));
        person1Floor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person1FloorActionPerformed(evt);
            }
        });

        person1Go.setBackground(new java.awt.Color(225, 225, 225));
        person1Go.setText("Go");
        person1Go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person1GoActionPerformed(evt);
            }
        });

        person1Location.setBackground(new java.awt.Color(200, 200, 200));
        person1Location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person1LocationActionPerformed(evt);
            }
        });

        person1Where.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        person1Where.setForeground(new java.awt.Color(50, 50, 50));
        person1Where.setText("Where?");

        person1WhatFloor.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        person1WhatFloor.setForeground(new java.awt.Color(50, 50, 50));
        person1WhatFloor.setText("What Floor?");

        person2Where.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        person2Where.setForeground(new java.awt.Color(50, 50, 50));
        person2Where.setText("Where?");

        person2WhatFloor.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        person2WhatFloor.setForeground(new java.awt.Color(50, 50, 50));
        person2WhatFloor.setText("What Floor?");

        personTwo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        personTwo.setForeground(new java.awt.Color(3, 3, 3));
        personTwo.setText("Person 2");

        person2Call.setBackground(new java.awt.Color(225, 225, 225));
        person2Call.setText("Call");
        person2Call.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person2CallActionPerformed(evt);
            }
        });

        person2Floor.setBackground(new java.awt.Color(200, 200, 200));
        person2Floor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person2FloorActionPerformed(evt);
            }
        });

        person2Go.setBackground(new java.awt.Color(225, 225, 225));
        person2Go.setText("Go");
        person2Go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person2GoActionPerformed(evt);
            }
        });

        person2Location.setBackground(new java.awt.Color(200, 200, 200));
        person2Location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person2LocationActionPerformed(evt);
            }
        });

        person3Call.setBackground(new java.awt.Color(225, 225, 225));
        person3Call.setText("Call");
        person3Call.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person3CallActionPerformed(evt);
            }
        });

        person3Floor.setBackground(new java.awt.Color(200, 200, 200));
        person3Floor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person3FloorActionPerformed(evt);
            }
        });

        person3Go.setBackground(new java.awt.Color(225, 225, 225));
        person3Go.setText("Go");
        person3Go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person3GoActionPerformed(evt);
            }
        });

        person3Location.setBackground(new java.awt.Color(200, 200, 200));
        person3Location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person3LocationActionPerformed(evt);
            }
        });

        person3Where.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        person3Where.setForeground(new java.awt.Color(50, 50, 50));
        person3Where.setText("Where?");

        person3WhatFloor.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        person3WhatFloor.setForeground(new java.awt.Color(50, 50, 50));
        person3WhatFloor.setText("What Floor?");

        personThree.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        personThree.setForeground(new java.awt.Color(3, 3, 3));
        personThree.setText("Person 3");

        person4WhatFloor.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        person4WhatFloor.setForeground(new java.awt.Color(50, 50, 50));
        person4WhatFloor.setText("What Floor?");

        personFour.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        personFour.setForeground(new java.awt.Color(3, 3, 3));
        personFour.setText("Person 4");

        person4Call.setBackground(new java.awt.Color(225, 225, 225));
        person4Call.setText("Call");
        person4Call.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person4CallActionPerformed(evt);
            }
        });

        person4Floor.setBackground(new java.awt.Color(200, 200, 200));
        person4Floor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person4FloorActionPerformed(evt);
            }
        });

        person4Go.setBackground(new java.awt.Color(225, 225, 225));
        person4Go.setText("Go");
        person4Go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person4GoActionPerformed(evt);
            }
        });

        person4Location.setBackground(new java.awt.Color(200, 200, 200));
        person4Location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person4LocationActionPerformed(evt);
            }
        });

        person4Where.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        person4Where.setForeground(new java.awt.Color(50, 50, 50));
        person4Where.setText("Where?");

        person5WhatFloor.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        person5WhatFloor.setForeground(new java.awt.Color(50, 50, 50));
        person5WhatFloor.setText("What Floor?");

        personFive.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        personFive.setForeground(new java.awt.Color(3, 3, 3));
        personFive.setText("Person 5");

        person4Call1.setBackground(new java.awt.Color(225, 225, 225));
        person4Call1.setText("Call");
        person4Call1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person4Call1ActionPerformed(evt);
            }
        });

        person5Floor.setBackground(new java.awt.Color(200, 200, 200));
        person5Floor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person5FloorActionPerformed(evt);
            }
        });

        person4Go1.setBackground(new java.awt.Color(225, 225, 225));
        person4Go1.setText("Go");
        person4Go1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person4Go1ActionPerformed(evt);
            }
        });

        person4Location1.setBackground(new java.awt.Color(200, 200, 200));
        person4Location1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person4Location1ActionPerformed(evt);
            }
        });

        person5Where.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        person5Where.setForeground(new java.awt.Color(50, 50, 50));
        person5Where.setText("Where?");

        floor1Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        floor1Label.setForeground(new java.awt.Color(3, 3, 3));
        floor1Label.setText("1");

        floor1.setBackground(new java.awt.Color(200, 200, 200));
        floor1.setForeground(new java.awt.Color(3, 3, 3));
        floor1.setText("X");
        floor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor1ActionPerformed(evt);
            }
        });

        floor2.setBackground(new java.awt.Color(200, 200, 200));

        floor2Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        floor2Label.setForeground(new java.awt.Color(3, 3, 3));
        floor2Label.setText("2");

        floor3Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        floor3Label.setForeground(new java.awt.Color(3, 3, 3));
        floor3Label.setText("3");

        floor3.setBackground(new java.awt.Color(200, 200, 200));

        floor4Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        floor4Label.setForeground(new java.awt.Color(3, 3, 3));
        floor4Label.setText("4");

        floor4.setBackground(new java.awt.Color(200, 200, 200));

        floor5Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        floor5Label.setForeground(new java.awt.Color(3, 3, 3));
        floor5Label.setText("5");

        floor5.setBackground(new java.awt.Color(200, 200, 200));

        floor7.setBackground(new java.awt.Color(200, 200, 200));

        floor7Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        floor7Label.setForeground(new java.awt.Color(3, 3, 3));
        floor7Label.setText("7");

        floor8Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        floor8Label.setForeground(new java.awt.Color(3, 3, 3));
        floor8Label.setText("8");

        floor8.setBackground(new java.awt.Color(200, 200, 200));

        floor9Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        floor9Label.setForeground(new java.awt.Color(3, 3, 3));
        floor9Label.setText("9");

        floor9.setBackground(new java.awt.Color(200, 200, 200));

        floor11Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        floor11Label.setForeground(new java.awt.Color(3, 3, 3));
        floor11Label.setText("11");

        floor11.setBackground(new java.awt.Color(200, 200, 200));

        floor6Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        floor6Label.setForeground(new java.awt.Color(3, 3, 3));
        floor6Label.setText("6");

        floor6.setBackground(new java.awt.Color(200, 200, 200));

        floor10Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        floor10Label.setForeground(new java.awt.Color(3, 3, 3));
        floor10Label.setText("10");

        floor10.setBackground(new java.awt.Color(200, 200, 200));

        stopButton.setBackground(new java.awt.Color(225, 225, 225));
        stopButton.setText("STOP");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        elevatorStatusLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        elevatorStatusLabel.setForeground(new java.awt.Color(3, 3, 3));
        elevatorStatusLabel.setText("Elevator Status");

        elevatorStatus.setBackground(new java.awt.Color(200, 200, 200));
        elevatorStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elevatorStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(floor3Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(floor3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(floor1Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(floor1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(floor2Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(floor2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(floor5Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(floor5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(floor4Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(floor4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(floor8Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(floor8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(floor6Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(floor6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(floor7Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(floor7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(floor9Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(floor9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(floor11Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(floor11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(floor10Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(floor10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(elevatorStatusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(elevatorStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stopButton)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(personFive, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(person4Call1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(person5WhatFloor)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(person5Floor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(person4Go1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(person5Where)
                                    .addComponent(person4Location1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(personTwo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(person2Call, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(person2WhatFloor)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(person2Floor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(person2Go)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(person2Where)
                                    .addComponent(person2Location)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(person1Call, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(personOne, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(person1WhatFloor)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(person1Floor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(person1Go)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(person1Where)
                                    .addComponent(person1Location, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(person3Call, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(personThree, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(person3Floor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(person3Go))
                                    .addComponent(person3WhatFloor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(person3Where)
                                    .addComponent(person3Location)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(personFour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(person4Call, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(person4WhatFloor)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(person4Floor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(person4Go)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(person4Where)
                                    .addComponent(person4Location))))
                        .addGap(194, 194, 194))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor11Label)
                            .addComponent(floor11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor10Label)
                            .addComponent(floor10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor9Label)
                            .addComponent(floor9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor8Label)
                            .addComponent(floor8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor7Label)
                            .addComponent(floor7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor6Label)
                            .addComponent(floor6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor5Label)
                            .addComponent(floor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor4Label)
                            .addComponent(floor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor3Label)
                            .addComponent(floor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor2Label)
                            .addComponent(floor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor1Label)
                            .addComponent(floor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(person1Where)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(person1Call, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(person1WhatFloor)
                                    .addComponent(personOne))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(person1Floor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(person1Go)
                                    .addComponent(person1Location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(person2Where)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(person2Call, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(person2WhatFloor)
                                    .addComponent(personTwo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(person2Floor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(person2Go)
                                    .addComponent(person2Location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(person3Where)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(person3Call, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(person3WhatFloor)
                                    .addComponent(personThree))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(person3Floor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(person3Go)
                                    .addComponent(person3Location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(person4Where)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(person4Call, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(person4WhatFloor)
                                    .addComponent(personFour))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(person4Floor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(person4Go)
                                    .addComponent(person4Location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(person5WhatFloor)
                                    .addComponent(personFive))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(person5Floor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(person4Go1)
                                    .addComponent(person4Location1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(person5Where)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(person4Call1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopButton)
                    .addComponent(elevatorStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elevatorStatusLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void person4Location1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person4Location1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_person4Location1ActionPerformed

    private void person4Go1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person4Go1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_person4Go1ActionPerformed

    private void person5FloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person5FloorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_person5FloorActionPerformed

    private void person4Call1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person4Call1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_person4Call1ActionPerformed

    private void person4LocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person4LocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_person4LocationActionPerformed

    private void person4GoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person4GoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_person4GoActionPerformed

    private void person4FloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person4FloorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_person4FloorActionPerformed

    private void person4CallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person4CallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_person4CallActionPerformed

    private void person3LocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person3LocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_person3LocationActionPerformed

    private void person3GoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person3GoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_person3GoActionPerformed

    private void person3FloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person3FloorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_person3FloorActionPerformed

    private void person3CallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person3CallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_person3CallActionPerformed

    private void person2LocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person2LocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_person2LocationActionPerformed

    private void person2GoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person2GoActionPerformed
        person2.setDestinationFloor(Integer.parseInt(person2Floor.getText()));
    }//GEN-LAST:event_person2GoActionPerformed

    private void person2FloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person2FloorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_person2FloorActionPerformed

    private void person2CallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person2CallActionPerformed
        person2.callElevator();
    }//GEN-LAST:event_person2CallActionPerformed

    private void person1LocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person1LocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_person1LocationActionPerformed

    private void person1GoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person1GoActionPerformed
        person1.setDestinationFloor(Integer.parseInt(person1Floor.getText()));
    }//GEN-LAST:event_person1GoActionPerformed

    private void person1FloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person1FloorActionPerformed
        
    }//GEN-LAST:event_person1FloorActionPerformed

    private void person1CallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person1CallActionPerformed
        person1.callElevator();
    }//GEN-LAST:event_person1CallActionPerformed

    private void elevatorStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elevatorStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elevatorStatusActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        continueToRun = false;
    }//GEN-LAST:event_stopButtonActionPerformed

    private void floor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor1ActionPerformed
    
   public boolean continueRunning()
    {
        return continueToRun;
    }
    
    public void updateElevatorStatus(int floor, String s) {

        elevatorStatus.setText(s);
        if (floor == 1) {
            floor1.setText("X");
        } else {
            floor1.setText("");
        }
        if (floor == 2) {
            floor2.setText("X");
        } else {
            floor2.setText("");
        }
        if (floor == 3) {
            floor3.setText("X");
        } else {
            floor3.setText("");
        }
        if (floor == 4) {
            floor4.setText("X");
        } else {
            floor4.setText("");
        }
        if (floor == 5) {
            floor5.setText("X");
        } else {
            floor5.setText("");
        }
        if (floor == 6) {
            floor6.setText("X");
        } else {
            floor6.setText("");
        }
        if (floor == 7) {
            floor7.setText("X");
        } else {
            floor7.setText("");
        }
        if (floor == 8) {
            floor8.setText("X");
        } else {
            floor8.setText("");
        }
        if (floor == 9) {
            floor9.setText("X");
        } else {
            floor9.setText("");
        }
        if (floor == 10) {
            floor10.setText("X");
        } else {
            floor10.setText("");
        }
        if (floor == 11) {
            floor11.setText("X");
        } else {
            floor11.setText("");
        }
        // TO DO....need to add code here to mark floor and erase all other floors
        // add all text fields in array, use for loop 
        // ORRRRRRRR if floor = 1, set text to X, else set text to blank.

    }
    
     public void updatePersonStatus(int id, String s)
    {
        // TO DO....based on respective id, update person text with string s
        if (id == 1)
        {
           person1Location.setText(s);
        }
        if (id == 2){
            person2Location.setText(s);
        }
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField elevatorStatus;
    private javax.swing.JLabel elevatorStatusLabel;
    private javax.swing.JTextField floor1;
    private javax.swing.JTextField floor10;
    private javax.swing.JLabel floor10Label;
    private javax.swing.JTextField floor11;
    private javax.swing.JLabel floor11Label;
    private javax.swing.JLabel floor1Label;
    private javax.swing.JTextField floor2;
    private javax.swing.JLabel floor2Label;
    private javax.swing.JTextField floor3;
    private javax.swing.JLabel floor3Label;
    private javax.swing.JTextField floor4;
    private javax.swing.JLabel floor4Label;
    private javax.swing.JTextField floor5;
    private javax.swing.JLabel floor5Label;
    private javax.swing.JTextField floor6;
    private javax.swing.JLabel floor6Label;
    private javax.swing.JTextField floor7;
    private javax.swing.JLabel floor7Label;
    private javax.swing.JTextField floor8;
    private javax.swing.JLabel floor8Label;
    private javax.swing.JTextField floor9;
    private javax.swing.JLabel floor9Label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton person1Call;
    private javax.swing.JTextField person1Floor;
    private javax.swing.JButton person1Go;
    private javax.swing.JTextField person1Location;
    private javax.swing.JLabel person1WhatFloor;
    private javax.swing.JLabel person1Where;
    private javax.swing.JButton person2Call;
    private javax.swing.JTextField person2Floor;
    private javax.swing.JButton person2Go;
    private javax.swing.JTextField person2Location;
    private javax.swing.JLabel person2WhatFloor;
    private javax.swing.JLabel person2Where;
    private javax.swing.JButton person3Call;
    private javax.swing.JTextField person3Floor;
    private javax.swing.JButton person3Go;
    private javax.swing.JTextField person3Location;
    private javax.swing.JLabel person3WhatFloor;
    private javax.swing.JLabel person3Where;
    private javax.swing.JButton person4Call;
    private javax.swing.JButton person4Call1;
    private javax.swing.JTextField person4Floor;
    private javax.swing.JButton person4Go;
    private javax.swing.JButton person4Go1;
    private javax.swing.JTextField person4Location;
    private javax.swing.JTextField person4Location1;
    private javax.swing.JLabel person4WhatFloor;
    private javax.swing.JLabel person4Where;
    private javax.swing.JTextField person5Floor;
    private javax.swing.JLabel person5WhatFloor;
    private javax.swing.JLabel person5Where;
    private javax.swing.JLabel personFive;
    private javax.swing.JLabel personFour;
    private javax.swing.JLabel personOne;
    private javax.swing.JLabel personThree;
    private javax.swing.JLabel personTwo;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables
    
    private boolean continueToRun = true;
    private Elevator myElevator = new Elevator(this);
    private Person person1 = new Person(1, this, myElevator);
    private Person person2 = new Person(2, this, myElevator);

}
